### ISSUE TITLE
BOM and/or KiCad files missing

### ISSUE THREAD

**Issue by SmakyTaky** [gpimblott/Z80Processor_Tester#1]
I have been trying to reproduce your tester. Ordered some PCBs using the gerber files. However, I was unable to find the KiCad V1 files and/or a BOM to identify all the components specs

**Comment by gpimblott** [comment]
The v02 Kicad files are the same at the moment so should give you the parts.  The attached image is a grab of the BOM.

![image](https://user-images.githubusercontent.com/2563249/128229382-63f3565d-f240-42c3-8edc-e456abfc786a.png)

**Comment by SmakyTaky** [comment]
Thanks… this helps a lot.
 
What programmer should I use for this microcontroller?

**Comment by SmakyTaky** [comment]
I just noticed some items missing... R1-R5 (is R5 here the same value 10K as in V2)?  R7-R11. I noticed all Leds have a 150 ohm current limiting resistor.. however, besides R5, the rest are not in this BOM. I was unable to identify the values from the photos on your post.

**Comment by gpimblott** [comment]
Hi, Sorry I should have paid more attention - v2 I have here is updated.

#Capacitor
C1 : 100uf

#LEDs & matching resisters
D3->D18 :  LED of your choice (I have used ultrabright blue)
D1 : Red or Green LED
R4 : Resister to match D1 (I used 150 Ohm again)
R16->R31 : Resister to match your LED I've used 150 Ohm

#Diode
D2 : 1n4148 diode

#Pulldown resisters (10K)
R1,2,3,5,6,7,8,9,10,11,12,13,14,15 : 10K resister

#PIC Chip
U1 : PIC 16F690

#5V Regulator
U2 : 7805

#Z80 
U3 : 40Pin ZIF socket

#ISCP header
J1: 6 header pins

#9V Power Socket
J2 :  2.1 mm barrel jack - watch the pin out I had to bodge mine in as it had the wrong pins placement


To programme the PIC chip you can either use a PICKIT 2 or 3 or a TL866II Plus programmer

I have also written up the build [on my blog](https://www.bitwrangler.uk/2021/07/07/z80-processor-tester/)

**Comment by SmakyTaky** [comment]
Excellent... thanks I have the TL866II Plus.. will let you know how it goes.

**Comment by SmakyTaky** [comment]
One more question.. I have been looking for a compatible barrel jack.. however, I have not been able to identify one that matches the pinout of the board. Do you happen to have a part number that may be compatible?

**Comment by gpimblott** [comment]
I used the wrong footprint for the barrel jack so I modded a standard one to fit the board.  I cut a leg off and snipped a corner of another :)
